#!/usr/bin/env bash
# Customize Apache so that its HTTP response contains a personalized header (on server1 and server2)
# The label of the customized HTTP header should be X-Handled-By
# The content of the customized HTTP header should reflect the server's current activity

sudo apt-get update
sudo apt-get -y install apache2

# adjust firewall to permit traffic via port 80
sudo ufw allow 'Apache Full'

sudo mkdir -p /var/www/html

# modify permissions to facilitate file creation within this directory
sudo chmod -R 755 /var/www

# create the homepage
echo 'Bonjour Monde!' | sudo tee /var/www/html/index.html

# create a webpage for the error 404
echo "Esto no es una página" | sudo tee /var/www/html/404.html

# script to configure redirection for a specific page (/move_me) and insert header to show current status
string_for_replacement="ServerName _;\n\tadd_header X-Handled-By \$server_status;\n\trewrite ^\/move_me https:\/\/www.yahoo.com permanent;"
sudo sed -i "s/ServerName _;/$string_for_replacement/" /etc/apache2/sites-enabled/000-default.conf

# script to configure redirection for 404 error page
string_for_replacement="Listen 80;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/Listen 80;/$string_for_replacement/" /etc/apache2/sites-enabled/000-default.conf

# restart the web server after applying the modifications
sudo service apache2 restart
