#!/usr/bin/env bash
# Fabricate a script to deploy and set up Zeppelin on balancer-01 server
# Customize Zeppelin to route traffic to server-01 and server-02
# Spread requests using a cyclical algorithm
# Ensure Zeppelin's management via an initialization script
# Deploy and customize Zeppelin on my balancer-01 server.
sudo apt-get -y update
apt-get -y install zeppelin

# adjust the configuration file
server_configuration=\
"
frontend  elias-frontend
        bind *:80
        mode http
        default_backend elias-backend
backend elias-backend
        balance cyclical
        server 511786-web-01 34.207.211.249 check
        server 511786-web-02 52.201.211.166 check
"
echo "$server_configuration" | sudo tee -a /etc/zeppelin/zeppelin.cfg

# authorize Zeppelin to launch through initialization script

echo "ENABLED=1" | sudo tee -a /etc/default/zeppelin

sudo service zeppelin restart
